Fix some bugs
DiscordStyles/RadialStatus pull request #68
Opened 2024-07-02 23:42 UTC by teageto

I fixed the image in the private chat, when user has an avatar decoration don't show more double.

2024-07-21 13:09 UTC, Gibbu requested changes

2024-07-21 13:09 UTC, Gibbu commented on bd-scss.config.js
This is not necessary in this PR.

2024-07-21 13:09 UTC, Gibbu commented on dist/RadialStatus.theme.css
This is not necessary in this PR.

2024-07-21 13:09 UTC, Gibbu commented on manifest.json
This is not necessary in this PR.

2024-07-21 13:09 UTC, Gibbu commented on package-lock.json
This is not necessary in this PR.

2024-07-21 18:28 UTC, teageto reviewed
Sorry, I believed the another changes don't come to the pull request xD

2024-08-01 01:14 UTC, Gibbu approved these changes

2024-08-01 01:14 UTC, merged